
-- Explore all objects in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES

 -- Explore all columns in the database
 SELECT * FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'dim_customers'

 SELECT DISTINCT i.TABLE_NAME 
 FROM INFORMATION_SCHEMA.COLUMNS AS i