 
 -- Database exploration
 SELECT * FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'dim_customers'
 

 SELECT *
 FROM gold.dim_customers

 -- Dimension_exploration

 SELECT DISTINCT country
 FROM gold.dim_customers

-- Measure exploration
SELECT COUNT(c.customer_id) totalCustomers FROM gold.dim_customers AS c;

SELECT COUNT( DISTINCT c.customer_id) totalCustomers FROM gold.dim_customers AS c;


-- Find the total numer of customers by countries
SELECT
	c.country AS country,
	COUNT(c.customer_id) AS totalCustomers
FROM gold.dim_customers AS c
GROUP BY c.country
ORDER BY COUNT(c.customer_id) DESC

-- Find the total numer of customers by Genders
SELECT
	c.gender AS Gender,
	COUNT(c.customer_id) AS totalCustomers
FROM gold.dim_customers AS c
GROUP BY c.gender
ORDER BY COUNT(c.customer_id) DESC

-- Find the total products by category
SELECT * FROM gold.dim_products

SELECT DISTINCT category FROM gold.dim_products;

SELECT DISTINCT product_id FROM gold.dim_products;

SELECT 
	p.category,
	COUNT(DISTINCT p.product_id) totalProducts
FROM gold.dim_products AS p
GROUP BY p.category
ORDER BY COUNT(DISTINCT p.product_id) DESC

-- what is the average cost in each category

SELECT 
	p.category,
	AVG(p.cost) AverageCost
FROM gold.dim_products AS p
GROUP BY p.category
ORDER BY AVG(p.cost) DESC

SELECT p.cost
FROM gold.dim_products AS p
WHERE p.cost IS NULL

-- Total revenue generated for each category

/* SELECT 
	p.category,
	SUM(p.cost) TotalRevenue
FROM gold.dim_products AS p
GROUP BY p.category
ORDER BY AVG(p.cost) DESC */

SELECT * FROM gold.dim_products;

SELECT * FROM gold.fact_sales;

-- Main query

SELECT 
	t.category,
	SUM(t.sales_amount) total_revenue
FROM (
		--- Subquery in FROM Cluase act as temporaty table
		SELECT 
		p.product_key,
		p.category,
		f.sales_amount
		FROM gold.dim_products AS p
		INNER JOIN gold.fact_sales AS f
		ON p.product_key = f.product_key
	) AS t
GROUP BY t.category
ORDER BY SUM(t.sales_amount) DESC;

SELECT 
-- p.product_key,
p.category,
SUM(f.sales_amount) totalRevenue
FROM gold.dim_products AS p
INNER JOIN gold.fact_sales AS f
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY SUM(f.sales_amount) DESC;

-- Total revenue generated by each customers

SELECT * FROM gold.fact_sales;

SELECT * FROM gold.dim_customers;


SELECT 
	f.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) totalRevenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key = c.customer_key
GROUP BY f.customer_key, c.first_name, c.last_name
ORDER BY SUM(f.sales_amount) DESC


SELECT 
	f.customer_key,
	SUM(f.sales_amount)
FROM gold.fact_sales AS f
GROUP BY f.customer_key;


SELECT * FROM INFORMATION_SCHEMA.COLUMNS

SELECT TOP 3 * FROM gold.dim_customers;

SELECT TOP 3 * FROM gold.dim_products;

SELECT TOP 3 * FROM gold.fact_sales;

-- Distribution of items sold across the countries

SELECT 
	c.country,
	SUM(f.quantity) items_sold
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY SUM(f.quantity) DESC